// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f9101639-2c88-40fd-b044-74978f68c2ab";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onHARPiSupplySWChange();

CloudSwitch hA_RPi_Supply_SW;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(hA_RPi_Supply_SW, READWRITE, ON_CHANGE, onHARPiSupplySWChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
